### ISSUE TITLE
VS Code 1.36 update -> "Unknown cipher"

### ISSUE THREAD

**Issue by oski1993** [ChuckJonas/vscode-salesforce-diff#8]
After allowing VS Code to update to 1.36, when using Salesforce Diff, am now getting the error, "No cipher".

[Mac OS 10.14.5, VS Code 1.36, SFDX version sfdx-cli/7.13.0-27dbcb37d3 darwin-x64 node-v10.15.3, Salesforce Extension Pack 46.4.0]

![Salesforce Diff (Workspace) 2019-07-03 14-38-38](https://user-images.githubusercontent.com/4913143/60626769-b647d580-9da0-11e9-9b69-b6818de38297.png)

> [2019-07-03 14:49:44.484] [renderer1] [error] Unknown cipher: Error: Unknown cipher
	at Cipheriv.createCipherBase (internal/crypto/cipher.js:79:18)
	at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:20)
	at new Cipheriv (internal/crypto/cipher.js:225:22)
	at Object.createCipheriv (crypto.js:105:10)
	at SecureBuffer.consume (/Users/user1/.vscode/extensions/chuckjonas.salesforce-diff-0.0.2/node_modules/@salesforce/core/lib/secureBuffer.js:74:31)
	at AuthInfoCrypto.init (/Users/user1/.vscode/extensions/chuckjonas.salesforce-diff-0.0.2/node_modules/@salesforce/core/lib/crypto.js:143:23)

**Comment by RuneSor** [comment]
Same here.

OSX 10.15 Beta (19A501i) - sfdx-cli/7.12.3-bfc421fa08 darwin-x64 node-v10.15.3
![Screenshot 2019-07-04 at 16 13 50](https://user-images.githubusercontent.com/11503600/60672947-e19cf400-9e76-11e9-9e71-04cdef143300.png)

[2019-07-04 16:16:52.989] [renderer5] [error] Unknown cipher: Error: Unknown cipher
	at Cipheriv.createCipherBase (internal/crypto/cipher.js:79:18)
	at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:20)
	at new Cipheriv (internal/crypto/cipher.js:225:22)
	at Object.createCipheriv (crypto.js:105:10)
	at SecureBuffer.consume (/Users/runesor/.vscode/extensions/chuckjonas.salesforce-diff-0.0.2/node_modules/@salesforce/core/lib/secureBuffer.js:74:31)
	at AuthInfoCrypto.init (/Users/runesor/.vscode/extensions/chuckjonas.salesforce-diff-0.0.2/node_modules/@salesforce/core/lib/crypto.js:143:23)

------------------------------

Let me know if there is anything i can share to help :)

**Comment by oski1993** [comment]
Additional logging I found:

```
[2019-08-15 17:47:08.256] [renderer2] [warning] UNRESPONSIVE extension host, 'chuckjonas.salesforce-diff' took 99% of 5908.603ms, saved PROFILE here: '/var/folders/15/fwbblzrn6ysc37sn49r08b2w4nvjdf/T/exthost-2310ed.cpuprofile' [{"id":"chuckjonas.salesforce-diff","total":5860036,"percentage":99},{"id":"gc","total":48405,"percentage":1}]
[2019-08-15 17:47:26.400] [renderer2] [error] Unknown cipher: Error: Unknown cipher
	at Cipheriv.createCipherBase (internal/crypto/cipher.js:79:18)
	at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:20)
	at new Cipheriv (internal/crypto/cipher.js:225:22)
	at Object.createCipheriv (crypto.js:105:10)
	at SecureBuffer.consume (/Users/lyang/.vscode/extensions/chuckjonas.salesforce-diff-0.0.2/node_modules/@salesforce/core/lib/secureBuffer.js:74:31)
	at AuthInfoCrypto.init (/Users/lyang/.vscode/extensions/chuckjonas.salesforce-diff-0.0.2/node_modules/@salesforce/core/lib/crypto.js:143:23)
```
![2019-08-15 17-50-13](https://user-images.githubusercontent.com/4913143/63136117-53dc1a80-bf85-11e9-8dbf-2b6bec7e0141.png)

**Comment by ChuckJonas** [comment]
@oski1993 merged and published your PR.  Working for me.  Please test
